{
  "openapi" : "3.0.0",
  "info" : {
    "title" : "UnDentifed Api",
    "description" : "This is the official undentified api.",
    "contact" : {
      "name" : "Dqrk",
      "email" : "staurospapadogiannopoulos@gmal.com"
    },
    "license" : {
      "name" : "Apache 2.0",
      "url" : "http://www.apache.org/licenses/LICENSE-2.0.html"
    },
    "version" : "1.0.0"
  },
  "servers" : [ {
    "url" : "https://champion-factually-goblin.ngrok-free.app"
  } ],
  "paths" : {
    "/api/users" : {
      "get" : {
        "description" : "Returns a list of artists",
        "parameters" : [ {
          "name" : "limit",
          "in" : "query",
          "description" : "Limits the number of items on a page",
          "required" : false,
          "style" : "form",
          "explode" : true,
          "schema" : {
            "type" : "integer"
          }
        }, {
          "name" : "offset",
          "in" : "query",
          "description" : "Specifies the page number of the artists to be displayed",
          "required" : false,
          "style" : "form",
          "explode" : true,
          "schema" : {
            "type" : "integer"
          }
        } ],
        "responses" : {
          "content" : { },
          "400" : {
            "description" : "Invalid request",
            "content" : {
              "application/json" : {
                "schema" : {
                  "type" : "object"
                }
              }
            }
          }
        }
      }
    }
  },
  "components" : { }
}